import markdown
from typing import Dict, Any

def generate_artistic_report(markdown_content: str, metadata: Dict[str, Any] = {}) -> str:
    """
    Converts markdown content into a stylized, artistic HTML report.
    """
    html_content = markdown.markdown(markdown_content, extensions=['extra', 'codehilite'])
    
    title = metadata.get("title", "Deep Research Report")
    date = metadata.get("date", "")
    
    html_template = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Lato:wght@300;400;700&display=swap');

        :root {{
            --primary-color: #2c3e50;
            --accent-color: #e74c3c;
            --bg-color: #fcfcfc;
            --text-color: #333;
            --paper-color: #ffffff;
        }}

        body {{
            font-family: 'Lato', sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            margin: 0;
            padding: 40px;
            line-height: 1.8;
        }}

        .container {{
            max-width: 800px;
            margin: 0 auto;
            background-color: var(--paper-color);
            padding: 60px 80px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.05);
            border-radius: 8px;
            position: relative;
        }}

        .container::before {{
            content: "";
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 6px;
            background: linear-gradient(90deg, var(--primary-color), var(--accent-color));
            border-radius: 8px 8px 0 0;
        }}

        h1, h2, h3, h4, h5, h6 {{
            font-family: 'Playfair Display', serif;
            color: var(--primary-color);
            margin-top: 1.5em;
            margin-bottom: 0.5em;
        }}

        h1 {{
            font-size: 3em;
            border-bottom: 2px solid var(--accent-color);
            padding-bottom: 10px;
            margin-top: 0;
        }}

        h2 {{
            font-size: 2em;
            border-left: 4px solid var(--primary-color);
            padding-left: 15px;
        }}

        p {{
            margin-bottom: 1.5em;
            font-size: 1.1em;
        }}

        blockquote {{
            font-family: 'Playfair Display', serif;
            font-style: italic;
            border-left: 3px solid var(--accent-color);
            margin: 20px 0;
            padding: 10px 20px;
            background-color: #f9f9f9;
            color: #555;
        }}

        code {{
            font-family: 'Consolas', monospace;
            background-color: #f0f0f0;
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 0.9em;
        }}

        pre {{
            background-color: #2c3e50;
            color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }}
        
        pre code {{
            background-color: transparent;
            color: inherit;
        }}

        a {{
            color: var(--accent-color);
            text-decoration: none;
            transition: color 0.3s;
        }}

        a:hover {{
            color: var(--primary-color);
            text-decoration: underline;
        }}

        .metadata {{
            font-size: 0.9em;
            color: #777;
            margin-bottom: 40px;
            font-style: italic;
        }}

        .footer {{
            margin-top: 60px;
            text-align: center;
            font-size: 0.8em;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 20px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="metadata">
            Generated by Artistic_DeepResearch | {date}
        </div>
        
        <div style="text-align: center; margin-bottom: 40px;">
            <img src="ArtisticDeepResearch.png" alt="Artistic Deep Research Logo" style="max-width: 200px;">
        </div>
        
        {html_content}

        <div class="footer">
            &copy; 2025 Artistic_DeepResearch. All rights reserved.
        </div>
    </div>
</body>
</html>
    """
    return html_template
